# Font
font_family MesloLGS NF
font_size 11
bold_font auto
italic_font auto
bold_italic_font auto
modify_font font_weight 100%

# Text rendering
text_composition_strategy platform
hinting_style light
antialiasing true
disable_ligatures no

# Cursor
cursor_shape block
cursor_blink true
cursor_stop_blinking_after 0
cursor_trail 3
cursor_trail_decay 0.1 0.4

# Terminal behavior
shell zsh
shell_integration disabled
scrollback_lines 2000
copy_on_select yes
select_by_word_characters @-./_~?&=%+#a

# Window
remember_window_size no
initial_window_width 640
initial_window_height 480
window_padding_width 25
window_border_width 1pt
draw_minimal_borders yes
hide_window_decorations yes
confirm_os_window_close 0

# Appearance
background_opacity 0.1
inactive_text_alpha 0.75
background_opacity 0.80

# Tabs
#tab_bar_style powerline
#bell_on_tab "🔔 "

# Mouse
mouse_hide_wait 0

# Scrollbar (hidden)
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0

# Misc
enable_audio_bell no
sync_to_monitor no

# Colors (external file)
include colors.conf
