# ~/.config/fuzzel/fuzzel.ini

# Schriftart anpassen (Nutzt deine installierten Nerd Fonts)
font=JetBrainsMono Nerd Font:size=12
icon-theme=Adwaita
prompt="❯ "
terminal=kitty

[colors]
# Format: RRGGBBAA (Die letzten beiden Zahlen steuern die Transparenz)
background=000000e6       # Reines Schwarz mit 90% Deckkraft
text=ffffffff             # Weißer Text
match=ffffffff            # Gefundene Buchstaben in Weiß
selection=ffffff22        # Graue Auswahl-Bar (Weiß mit hoher Transparenz)
selection-text=ffffffff   # Weißer Text bei Auswahl
border=fffffffff          # Weißer dünner Rahmen um das Fenster

[border]
width=1
radius=5
