# ~/.config/hypr/hyprlock.conf

background {
    monitor =
    path = /home/samsour/Bilder/bw-wallpaper-1.jpg
    # Ein feiner Weichzeichner, damit die Uhrzeit gut lesbar ist
    blur_passes = 2
    blur_size = 6
    noise = 0.01
}

# DIE UHRZEIT (Zentriert, groß und weiß)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(255, 255, 255, 0.9)
    font_size = 95
    font_family = JetBrainsMonoNL Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

# DAS DATUM (Direkt unter der Uhrzeit)
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d. %B')"
    color = rgba(255, 255, 255, 0.6)
    font_size = 22
    font_family = JetBrainsMonoNL Nerd Font
    position = 0, 70
    halign = center
    valign = center
}

# DAS PASSWORT-EINGABEFELD
input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.25 
    dots_spacing = 0.3
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(20, 20, 20, 0.7) # Dunkle Kapsel, passend zur Waybar
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <i>Passwort eingeben...</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}
