# Neue Hyprpaper Syntax für aktuelle Versionen
preload = /home/samsour/Bilder/bw-wallpaper-3.jpg

wallpaper {
    monitor = DP-1
    path = /home/samsour/Bilder/bw-wallpaper-3.jpg
    fit_mode = cover
}

# Optional: Text unten ausschalten
splash = false
