# ~/.config/hypr/hyprlock.conf

background {
    monitor =
    path = /home/samsour/Bilder/bw-wallpaper-3.jpg
    
    blur_passes = 2
    blur_size = 6
    noise = 0.075
}

# time
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    color = rgba(255, 255, 255, 0.9)
    font_size = 95
    font_family = JetBrainsMonoNL Nerd Font
    position = 0, 150
    halign = center
    valign = center
}

# date
label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %d. %B')"
    color = rgba(255, 255, 255, 0.6)
    font_size = 22
    font_family = JetBrainsMonoNL Nerd Font
    position = 0, 70
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 200, 48
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.1)
    inner_color = rgba(20, 20, 20, 0.7)
    font_color = rgb(255, 255, 255)
    fade_on_empty = false
    placeholder_text = <i>Password</i>
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
}
